Craig-RogersInvestmentsLLC = "0AfC2exeaZIJ3f6"
credentials_usernames_ondra_username = 'ondrej.svoboda@keboola.com'
credentials_usernames_ondra_name = 'Ondřej Svoboda'
credentials_usernames_ondra_password = 'xxx'

kbc_url = "https://connection.keboola.com/"
kbc_token = "9525-581129-c6XWZMcvBVxpK5cL5aZS50dkFr22lQJrt1c0bkP9"
kbc_token_master = "9525-621032-qDYsCaAzbfVNBC9vDWSebROGx3cGnEpSJstpwccq"
