kbc_url = "https://connection.keboola.com/"
kbc_token = "9525-581129-c6XWZMcvBVxpK5cL5aZS50dkFr22lQJrt1c0bkP9"
kbc_token_master = "9525-621032-qDYsCaAzbfVNBC9vDWSebROGx3cGnEpSJstpwccq"

[passwords]
# Follow the rule: username = "password"
alice_foo = "streamlit123"
bob_bar = "mycrazypw"
FUGEN-2EnterprisesLLC = "YOH1jJxLhWfkY6A"
Craig-RogersInvestmentsLLC = "0AfC2exeaZIJ3f6"
FireFoodsLLC = "qBvTDBDDQSXzX79"
FIREZONALLC = "JAJmYZOjGup79c1"
PatelSubsInc = "dt6dkNwl6cLAvmk"
GWLTDHighpointeLLC = "SuteBKy1PoG4GLd"
EdensSubShopILLC = "6sw3tIBeK0jnzcE"
RiverCitySubsInc = "xCzrjIkaVVw2j3Q"
MZSubsofUtahInc = "81GpfAun5MhCuXJ"
WHIDDENPRISELLC = "I7IjNt6iCP8GxWW"
WHIDDENPRISEIILLC = "3N0YR5UBhzMbKzD"
EdensSubShopIILLC = "YOH1jJxLhWfkY6A"
EngelstadFHSFourLLC = "vICmAj5lNJ8Xwxd"
FireStationNo2810LLC = "joMQNKZDY7A1S3c"
3rdFireLLC = "Se0ZbutTLrlkfX6"
SANDWICHESARELIFELLC = "joMQNKZDY7A1S3c"
FERGUSONSFOURFIRELLC = "HUJwKCueq9sv8gp"
